development: localhost:6379
test: localhost:6381
staging: staging.tour-builder.digital-footsteps.com:6379
qa: localhost:6379
qa_dev: localhost:6380
production: pre-production.tour-builder.digital-footsteps.com:6379
